spring:
  redis:
    database: 13
    host: localhost
    port: 6379
#    password: localhost
    timeout: 6000
    lettuce:
      pool:
        max-active: 5000 # 连接池最大连接数
        max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 5 # 连接池中的最小空闲连接
        max-idle: 2000 # 连接池中的最大空闲连接
#logging:
#  level: debug
